# Generated by Django 5.1.1 on 2024-11-22 15:52

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_room_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["name"]
            ),
        ),
    ]
