# Generated by Django 5.2 on 2026-03-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
